image: hosttoday/ht-docker-node:latest

stages:
- test
- release
- page

testLEGACY:
  stage: test
  script:
    - npmci test legacy
  tags:
    - docker

testLTS:
  stage: test
  script:
    - npmci test lts
  tags:
    - docker
    
testSTABLE:
  stage: test
  script:
    - npmci test stable
  tags:
    - docker

release:
  stage: release
  script:
    - npmci publish npm
    - npmci trigger
  only:
    - tags
  tags:
    - docker
    
pages:
  stage: page
  script:
  - npmci test lts
  - mkdir .public
  - cp -r test/assets/docs/ .public
  - cp -r test/assets/coverage/ .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - tags